//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Global.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizContentLink
    {
        public int LinkId { get; set; }
        public int QuizId { get; set; }
        public int ContentId { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
